In [1]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#importing dataset
dataset = pd.read_csv(r"C:\Users\muthuraj.jayaseelan\insurance.csv")

In [2]:
dataset.shape

(1338, 7)

In [3]:
dataset.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [4]:
x = dataset.iloc[:,[0,3]]
y = dataset.iloc[:,6]

In [5]:
x.head()

age  children
0   19         0
1   18         1
2   28         3
3   33         0
4   32         0

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [8]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.30,random_state=0)

In [9]:
scaler = StandardScaler().fit(x_train)

In [10]:
x_train_scaled = scaler.transform(x_train)

In [11]:
print(x_train_scaled)

[[-1.5330973  -0.89833872]
 [-0.03364163 -0.89833872]
 [ 0.89459283  3.25603402]
 ...
 [ 0.03776102 -0.89833872]
 [-1.46169465 -0.89833872]
 [-0.46205754 -0.06746417]]


In [17]:
print(x_train_scaled.mean(axis=0))
print(x_train_scaled.std(axis=0))

[-4.55476113e-17  6.83214169e-17]
[1. 1.]


In [16]:
scaler.mean_

array([39.47115385,  1.08119658])

In [18]:
scaler2 = StandardScaler().fit(x_test)
x_test_scaled = scaler.transform(x_test)

In [19]:
print(x_test_scaled)

[[ 0.89459283 -0.06746417]
 [ 0.53757957 -0.06746417]
 [ 0.60898222  0.76341038]
 [ 1.53721668 -0.89833872]
 [ 0.82319018 -0.89833872]
 [-0.39065489 -0.89833872]
 [-1.5330973  -0.89833872]
 [ 0.82319018  1.59428492]
 [-0.10504428  1.59428492]
 [-0.60486284  1.59428492]
 [-0.39065489  1.59428492]
 [ 0.75178752  0.76341038]
 [ 0.25196897 -0.06746417]
 [-0.46205754 -0.89833872]
 [-0.89047344 -0.89833872]
 [ 0.75178752  1.59428492]
 [ 1.46581403 -0.89833872]
 [-0.96187609 -0.06746417]
 [-0.10504428  0.76341038]
 [-1.390292   -0.89833872]
 [ 0.82319018  0.76341038]
 [ 1.18020343  0.76341038]
 [ 0.89459283 -0.89833872]
 [ 0.53757957 -0.89833872]
 [-1.2474867  -0.89833872]
 [-0.53346019 -0.06746417]
 [-0.81907079 -0.89833872]
 [ 0.03776102  1.59428492]
 [-0.60486284 -0.89833872]
 [ 0.39477427  0.76341038]
 [ 0.03776102  1.59428492]
 [ 1.39441138 -0.06746417]
 [ 1.60861933 -0.89833872]
 [ 1.10880078 -0.89833872]
 [-1.10468139 -0.89833872]
 [-0.67626549 -0.89833872]
 [ 0.46617692  0.76341038]
 

In [20]:
#building a model
from sklearn.linear_model import LinearRegression
regress = LinearRegression()
regress.fit(x_train_scaled,y_train)

LinearRegression()

In [21]:
#prediction
y_predict = regress.predict(x_test_scaled)
datasetComparison = pd.DataFrame({'Actual: ':y_test,'Predicted: ':y_predict})
print(datasetComparison)

         Actual:    Predicted: 
578    9724.53000  16113.206976
610    8547.69130  14944.559892
569   45702.02235  15770.301860
1034  12950.07120  17624.759176
198    9644.25250  15287.465008
...           ...           ...
1261   3277.16100  10503.700974
494   17942.10600  10643.632710
97    10226.28420  16222.382675
418   14418.28040  18917.959977
920   13451.12200  17858.488593

[402 rows x 2 columns]
