## What is NumPy?
• NumPy is a Python library used for working with arrays.<br>
• It also has functions for working in domain of linear algebra, fourier
transform, and matrices.<br>
• NumPy stands for Numerical Python.<br>
• In Python we have lists that serve the purpose of arrays, but they are
slow to process.<br>
• NumPy aims to provide an array object that is up to 50x faster than
traditional Python lists.<br>
• The array object in NumPy is called ndarray, it provides a lot of
supporting functions that make working with ndarray very easy.<br>
• Arrays are very frequently used in data science, where speed and
resources are very important.<br>
• NumPy is a Python library and is written partially in Python, but most
of the parts that require fast computation are written in C or C++.

In [1]:
#Example
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## Dimensions in Arrays
A dimension in arrays is one level of array depth (nested arrays).<br>
nested array: are arrays that have arrays as their elements<br>

## 0-D Arrays
0-D arrays, or Scalars, are the elements in an array.<br>
Each value in an array is a 0-D array.

In [2]:
#Example
import numpy as np
arr = np.array(42)
print(arr)

42


## 1-D Arrays

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.<br>
These are the most common and basic arrays.

In [3]:
#Example
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


## 2-D Arrays

An array that has 1-D arrays as its elements is called a 2-D array.<br>
These are often used to represent matrix or 2nd order tensors.

In [4]:
#Example
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


## 3-D arrays

An array that has 2-D arrays (matrices) as its elements is called 3-D array.<br>
These are often used to represent a 3rd order tensor.

In [5]:
#Example
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## Check Number of Dimensions?

NumPy Arrays provides the ndim attribute that returns an integer that tells us
how many dimensions the array have.

In [6]:
#Example
import numpy as np
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## Higher Dimensional Arrays

An array can have any number of dimensions.<br>
When the array is created, you can define the number of dimensions by using
the ndmin argument.

In [7]:
#Example
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


## Access Array Elements

Array indexing is the same as accessing an array element.<br>
You can access an array element by referring to its index number.<br>
The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1

In [8]:
#Example
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[0])
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

1
7


## Access 2-D Arrays

To access elements from 2-D arrays we can use comma separated integers<br>
representing the dimension and the index of the element.<br>
Think of 2-D arrays like a table with rows and columns, where the row represents the dimension and the index represents the column.

In [9]:
#Example
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


## Access 3-D Arrays

To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [10]:
#Example
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


## Negative Indexing

Use negative indexing to access an array from the end.

In [11]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


## Reshaping arrays

Reshaping means changing the shape of an array.<br>
The shape of an array is the number of elements in each dimension.<br>
By reshaping we can add or remove dimensions or change number of elements in each dimension.<br>

## Reshape From 1-D to 2-D
Convert the following 1-D array with 12 elements into a 2-D array.<br>
The outermost dimension will have 4 arrays, each with 3 elements:<br>

In [12]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Reshape From 1-D to 3-D
Convert the following 1-D array with 12 elements into a 3-D array.<br>
The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

In [13]:
#Example
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## Flattening the arrays

Flattening array means converting a multidimensional array into a 1D array.<br>
We can use reshape(-1) to do this.

In [14]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [15]:
#Sort the array:
import numpy as np
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[0 1 2 3]
[[2 3 4]
 [0 1 5]]
